version: "3"

services:
  pg:
    image: "postgres:latest"
    container_name: "bossabox-postresql"
    restart: always
    volumes:
      - ./data/postgres/db:/data/db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=vuttr_db

  redis:
    image: redis:alpine
    container_name: "bossabox-redis"
    ports:
      - "${REDIS_PORT}:6379"