name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Build package
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
      - name: Test code
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test
